Feature/our projects
Ukrainer-In-Trier/ukrainer-in-trier.github.io pull request #64
Opened 2022-12-18 08:02 UTC by pyataevma

Changed the style of the page "Our projects". The aspect ratio of images is changed to 1:1.  Old versions of images are saved in the folder "static/projectsImg-old"
![03](https://user-images.githubusercontent.com/102365963/208287649-f6045144-0db4-4728-b7b6-3aa08eec6dfd.png)

2023-01-13 13:32 UTC, Likita requested changes

2023-01-13 13:32 UTC, Likita commented on content/en/projects/art.md
> +author: "Anauthor"
Всех авторов можно удалить

2023-01-13 13:32 UTC, Likita commented on content/en/projects/cultural.md
> +        text="Children should have access to the same lives as their peers in Ukraine. Many of them will return home - that's why our task is to make a minimal ``gap'' in knowledge. And school is a g
Кавычки неправильные

2023-01-13 13:32 UTC, Likita commented on content/en/projects/educational-projects.md
> +Teachers, even far from home, nurture the Ukrainian language and impart knowledge to young children.
На отдельных страницах надо выровнять текст по центру

2023-01-13 13:32 UTC, Likita commented on content/fr/projects/cultural.md
> +     text="Nous organisons divers événements. Autant que possible dans une ``famille'', une ambiance si indigène. Soirées, pique-niques, promenades dans la ville - nous mettons tout cela en œuvre grâ
проверить везде кавычки типо ``famille''

2023-01-13 13:32 UTC, Likita commented on content/fr/projects/cultural.md
> +   >}}
Closing tag?

2023-01-13 13:32 UTC, Likita commented on content/uk/projects/cultural.md
> +    text="Діти повинні мати доступ до тих жи зань, що і їхні однолітки в Україні. Багато з них поверниться додому - тому наша задача,  зробити мінімальний ``пробіл`` у знаннях. Та й школа - це чудова
кавычки внутри текста

2023-01-13 13:32 UTC, Likita commented on content/uk/projects/psych-help.md
> +</div>Кожен українець має можливість звернутись до нас по допомогу і обов'язково отримає її.
Текст должен быть выровнен. Пустые дивы не нужны

2023-01-13 13:32 UTC, Likita commented on layouts/shortcodes/cultural-item.html
> +</div>
Добавить пустую строку

2023-01-13 13:32 UTC, Likita commented on layouts/shortcodes/cultural-table.html
> +</div>
Тут везде и далее пустые строки в конце

2023-01-14 03:01 UTC, pyataevma commented on content/fr/projects/cultural.md
> +   >}}
Здесь вроде бы все нормально. Есть и открывающий и закрывающий тэги.

2023-01-14 03:04 UTC, pyataevma commented on content/en/projects/educational-projects.md
> +Teachers, even far from home, nurture the Ukrainian language and impart knowledge to young children.
Я выровнял. Но больше никакого форматирования для отдельных страниц пока не делал, например, ширину не устанавливал. Это же пока черновой контент. Там явно будет больше и форматирование сложнее.

2023-01-14 03:10 UTC, pyataevma commented on content/en/projects/art.md
> +author: "Anauthor"
Удалил

2023-01-14 03:11 UTC, pyataevma commented on content/en/projects/cultural.md
> +        text="Children should have access to the same lives as their peers in Ukraine. Many of them will return home - that's why our task is to make a minimal ``gap'' in knowledge. And school is a g
заменил на \"

2023-01-14 03:11 UTC, pyataevma commented on content/uk/projects/psych-help.md
> +</div>Кожен українець має можливість звернутись до нас по допомогу і обов'язково отримає її.
Исправил

2023-01-14 03:12 UTC, pyataevma commented on layouts/shortcodes/cultural-item.html
> +</div>
Добавил везде

2023-01-20 14:03 UTC, Likita approved these changes

2023-01-20 14:03 UTC, merged