added content and style to all pages Free Birds
Ukrainer-In-Trier/ukrainer-in-trier.github.io pull request #70
Opened 2022-12-30 19:21 UTC by Irina-M-lu

Added content and style to all language pages. German and French must be checked

https://www.notion.so/vasilika/d4d035b5b37640f1b55834ba93537410?v=38a982151bec48ca9534846bdd004882&p=09674865dee049898f6f190dc6b5019e&pm=s

2023-01-05 18:40 UTC, Likita requested changes

2023-01-05 18:40 UTC, Likita commented on content/de/projects/free-birds.md
> +        <p class='text-white py-4 text-xl text-justify'>Das geheimnisvolle antike Trier zieht Talente an, bindet und eint sie. Das ist richtig, bisher unbekannte Leute - konnten ein einziges unglaubl
They have another text in German

2023-01-06 21:50 UTC, Irina-M-lu commented on content/de/projects/free-birds.md
> +        <p class='text-white py-4 text-xl text-justify'>Das geheimnisvolle antike Trier zieht Talente an, bindet und eint sie. Das ist richtig, bisher unbekannte Leute - konnten ein einziges unglaubl
It is not text it's just wix builder discription :)

2023-01-07 16:11 UTC, Likita commented on content/de/projects/free-birds.md
> +        <p class='text-white py-4 text-xl text-justify'>Das geheimnisvolle antike Trier zieht Talente an, bindet und eint sie. Das ist richtig, bisher unbekannte Leute - konnten ein einziges unglaubl
Тогда нужно исправить конфликты. Там серый цвет по-разному написан

2023-01-10 18:25 UTC, Likita approved these changes

2023-01-10 18:25 UTC, merged